# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{faceb}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathieu Fosse"]
  s.date = %q{2010-04-05}
  s.default_executable = %q{console}
  s.description = %q{Facebook library}
  s.email = %q{mathieu@tigerlilyapps.com}
  s.executables = ["console"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/console",
     "faceb.gemspec",
     "features/faceb-session.feature",
     "features/step_definitions/facebook-session_steps.rb",
     "features/support/env.rb",
     "lib/faceb.rb",
     "lib/faceb/api.rb",
     "lib/faceb/base.rb",
     "lib/faceb/rails.rb",
     "lib/faceb/rails/api.rb",
     "lib/faceb/rails/base.rb",
     "lib/faceb/rails/configuration.rb",
     "lib/faceb/rails/controller.rb",
     "lib/faceb/rails/generators.rb",
     "lib/faceb/rails/generators/config/USAGE",
     "lib/faceb/rails/generators/config/config_generator.rb",
     "lib/faceb/rails/generators/config/templates/faceb.yml",
     "lib/faceb/rails/generators/fb_connect/USAGE",
     "lib/faceb/rails/generators/fb_connect/fb_connect_generator.rb",
     "lib/faceb/rails/generators/fb_connect/templates/xd_receiver.html",
     "lib/faceb/rails/generators/fb_connect/templates/xd_receiver_ssl.html",
     "lib/faceb/rails/rails_23_init.rb",
     "lib/faceb/rails/railtie.rb",
     "lib/faceb/rails/tasks.rb",
     "lib/faceb/rails/tasks/faceb.tasks",
     "lib/faceb/rails/tasks/tunnel.tasks",
     "lib/faceb/session.rb",
     "spec/faceb_api_spec.rb",
     "spec/faceb_base_spec.rb",
     "spec/faceb_session_spec.rb",
     "spec/rails/config_generator_spec.rb",
     "spec/rails/configuration_sepc.rb",
     "spec/rails/controller_spec.rb",
     "spec/rails/fb_connect_generator_spec.rb",
     "spec/rails/railtie_spec.rb",
     "spec/rails_app/app/controllers/application_controller.rb",
     "spec/rails_app/app/controllers/posts_controller.rb",
     "spec/rails_app/app/helpers/application_helper.rb",
     "spec/rails_app/config.ru",
     "spec/rails_app/config/application.rb",
     "spec/rails_app/config/boot.rb",
     "spec/rails_app/config/database.yml",
     "spec/rails_app/config/environment.rb",
     "spec/rails_app/config/environments/development.rb",
     "spec/rails_app/config/environments/production.rb",
     "spec/rails_app/config/environments/test.rb",
     "spec/rails_app/config/faceb.yml",
     "spec/rails_app/config/initializers/backtrace_silencers.rb",
     "spec/rails_app/config/initializers/cookie_verification_secret.rb",
     "spec/rails_app/config/initializers/inflections.rb",
     "spec/rails_app/config/initializers/mime_types.rb",
     "spec/rails_app/config/initializers/session_store.rb",
     "spec/rails_app/config/locales/en.yml",
     "spec/rails_app/config/routes.rb",
     "spec/rails_app/log/development.log",
     "spec/rails_app/log/production.log",
     "spec/rails_app/log/server.log",
     "spec/rails_app/log/test.log",
     "spec/rails_app/public/404.html",
     "spec/rails_app/public/422.html",
     "spec/rails_app/public/500.html",
     "spec/rails_app/public/favicon.ico",
     "spec/rails_app/public/javascripts/application.js",
     "spec/rails_app/public/javascripts/controls.js",
     "spec/rails_app/public/javascripts/dragdrop.js",
     "spec/rails_app/public/javascripts/effects.js",
     "spec/rails_app/public/javascripts/prototype.js",
     "spec/rails_app/public/javascripts/rails.js",
     "spec/rails_app/public/stylesheets/.gitkeep",
     "spec/rails_app/script/rails",
     "spec/rails_spec_helper.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tigerlily/faceb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Facebook library}
  s.test_files = [
    "spec/faceb_api_spec.rb",
     "spec/faceb_base_spec.rb",
     "spec/faceb_session_spec.rb",
     "spec/rails/config_generator_spec.rb",
     "spec/rails/configuration_sepc.rb",
     "spec/rails/controller_spec.rb",
     "spec/rails/fb_connect_generator_spec.rb",
     "spec/rails/railtie_spec.rb",
     "spec/rails_app/app/controllers/application_controller.rb",
     "spec/rails_app/app/controllers/posts_controller.rb",
     "spec/rails_app/app/helpers/application_helper.rb",
     "spec/rails_app/config/application.rb",
     "spec/rails_app/config/boot.rb",
     "spec/rails_app/config/environment.rb",
     "spec/rails_app/config/environments/development.rb",
     "spec/rails_app/config/environments/production.rb",
     "spec/rails_app/config/environments/test.rb",
     "spec/rails_app/config/initializers/backtrace_silencers.rb",
     "spec/rails_app/config/initializers/cookie_verification_secret.rb",
     "spec/rails_app/config/initializers/inflections.rb",
     "spec/rails_app/config/initializers/mime_types.rb",
     "spec/rails_app/config/initializers/session_store.rb",
     "spec/rails_app/config/routes.rb",
     "spec/rails_spec_helper.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<rack-facebook>, [">= 0.0.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_development_dependency(%q<rr>, [">= 0.10.10"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_dependency(%q<rack-facebook>, [">= 0.0.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<rr>, [">= 0.10.10"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
    s.add_dependency(%q<rack-facebook>, [">= 0.0.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<rr>, [">= 0.10.10"])
  end
end

